# Generated by Django 6.0.3 on 2026-03-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('object_type', models.CharField(help_text='e.g., Human, Planet, Star, Galaxy', max_length=100)),
                ('scale_order', models.IntegerField(help_text='Order in zoom sequence (1=Human, 2=Earth, etc.)')),
                ('size_description', models.CharField(help_text='e.g., 1.7 meters or 105,700 light-years', max_length=200)),
                ('distance_from_earth', models.CharField(default='0', help_text='e.g., 0, 93 million miles, etc.', max_length=200)),
                ('description', models.TextField(help_text='Formation facts, interesting details')),
                ('image_url', models.URLField(blank=True, help_text='URL to an image or texture to use in 3D', null=True)),
                ('base_color', models.CharField(default='#FFFFFF', help_text='Hex color or CSS color name for 3D representation', max_length=20)),
                ('size_in_meters', models.FloatField(help_text='Approximate scale in meters for 3D engine positioning')),
            ],
            options={
                'ordering': ['scale_order'],
            },
        ),
    ]
