# Generated by Django 6.0.3 on 2026-03-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celestialobject',
            name='comparison',
            field=models.TextField(blank=True, help_text='e.g. 1 million Earths fit inside the Sun', null=True),
        ),
    ]
